#!/bin/sh

# luci language
uci set luci.main.lang=zh_cn
uci commit luci


#
/etc/init.d/dnscrypt-proxy stop


# system
uci batch <<EOF
set system.@system[0].hostname='Raspberry_Pi'
set system.@system[0].timezone='PST8PDT,M3.2.0,M11.1.0'
set system.@system[0].zonename='America/Los Angeles'
uci delete system.ntp.enable_server
set system.ntp.server="cn.ntp.org.cn"
add_list system.ntp.server="edu.ntp.org.cn"
add_list system.ntp.server="ntp.ntsc.ac.cn"
add_list system.ntp.server="ntp.tuna.tsinghua.edu.cn"
set system.ntp.use_dhcp='0'
system.@imm_init[0].opkg_mirror='https://downloads.immortalwrt.org'
EOF
uci commit system


# network config
uci batch <<EOF
delete network.lan.ip6assign
delete network.globals.ula_prefix
set network.lan.gateway='192.168.177.1'
set network.lan.dns='127.0.0.1'
set network.lan6=interface
set network.lan6.proto='dhcpv6'
set network.lan6.device='@lan'
set network.lan6.reqaddress='try'
set network.lan6.reqprefix='auto'
set network.lan6.dns='::1'
EOF
uci commit network
/etc/init.d/network restart


# firewall
uci batch <<EOF
delete firewall.@defaults[0].syn_flood='0'
set firewall.@defaults[0].input='ACCEPT'
set firewall.@defaults[0].forward='ACCEPT'
set firewall.@defaults[0].fullcone6='1'
delete firewall.@zone[0].network
set firewall.@zone[0].network='lan'
add_list firewall.@zone[0].network='lan6'
EOF
uci commit firewall
/etc/init.d/firewall restart


# DHCP & dnsmasq
uci batch <<EOF
set dhcp.@dnsmasq[0].boguspriv='1'
set dhcp.@dnsmasq[0].dns_redirect='0'
set dhcp.@dnsmasq[0].expandhosts='0'
set dhcp.@dnsmasq[0].authoritative='0'
set dhcp.@dnsmasq[0].interface='lan'
set dhcp.@dnsmasq[0].dnsseccheckunsigned='0'
set dhcp.@dnsmasq[0].filter_aaaa='1'
set dhcp.@dnsmasq[0].nonegcache='1'
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
delete dhcp.lan.ra_slaac
delete dhcp.lan.ra_flags
delete dhcp.lan.ndp
set dhcp.lan.ignore='1'
set dhcp.lan.dynamicdhcp='0'
set dhcp.@dnsmasq[0].server='127.0.0.1#5335'
EOF
uci commit dhcp
/etc/init.d/dnsmasq restart


#mosdns
uci batch <<EOF
set mosdns.config.enabled='1'
set mosdns.config.listen_port='5335'
set mosdns.config.geo_auto_update='1'
set mosdns.config.geo_update_week_time='1'
set mosdns.config.geo_update_day_time='2'
set mosdns.config.dump_file='1'
set mosdns.config.concurrent='2'
set mosdns.config.custom_local_dns='1'
set mosdns.config.dns_leak='1'
set mosdns.config.bootstrap_dns='8.8.8.8'
set mosdns.config.local_dns='114.114.114.114'
add_list mosdns.config.local_dns='223.5.5.5'
set mosdns.config.remote_dns='udp://127.0.0.53:53'
set mosdns.config.enable_ecs_remote='0'
set mosdns.config.dump_interval='3600'
EOF
uci commit mosdns
/etc/init.d/mosdns restart


# fix distfeeds
cat << "EOF" > /etc/opkg/distfeeds.conf
src/gz immortalwrt_core https://downloads.immortalwrt.org/snapshots/targets/bcm27xx/bcm2710/packages
src/gz immortalwrt_base https://downloads.immortalwrt.org/snapshots/packages/aarch64_cortex-a53/base
src/gz immortalwrt_luci https://downloads.immortalwrt.org/snapshots/packages/aarch64_cortex-a53/luci
src/gz immortalwrt_packages https://downloads.immortalwrt.org/snapshots/packages/aarch64_cortex-a53/packages
src/gz immortalwrt_routing https://downloads.immortalwrt.org/snapshots/packages/aarch64_cortex-a53/routing
src/gz immortalwrt_telephony https://downloads.immortalwrt.org/snapshots/packages/aarch64_cortex-a53/telephony
EOF


# argon
uci batch <<EOF
set argon.@global[0].primary='#bc1142'
set argon.@global[0].dark_primary='#bc1142'
set argon.@global[0].blur='10'
set argon.@global[0].blur_dark='10'
set argon.@global[0].transparency='0.5'
set argon.@global[0].transparency_dark='0.5'
set argon.@global[0].mode='normal'
set argon.@global[0].online_wallpaper='none'
EOF
uci commit argon


# dropbear
uci commit dropbear
/etc/init.d/dropbear restart


#
/etc/init.d/dnscrypt-proxy start

exit 0
