#!/bin/bash

/etc/init.d/dropbear stop
/etc/init.d/passwall2 stop
/etc/init.d/haproxy stop
/etc/init.d/udp2raw stop
/etc/init.d/udpspeeder stop
/etc/init.d/kcptun stop
/etc/init.d/mosdns stop

sysupgrade -r /etc/backup/Raspberry_Pi3B_us_lanx0.tar.gz
rm -rf /etc/backup

uci commit system
uci commit network
/etc/init.d/network restart
uci commit dhcp
/etc/init.d/dnsmasq restart
uci commit mosdns
uci commit argon

/etc/init.d/passwall2 start
/etc/init.d/haproxy start
/etc/init.d/udp2raw start
/etc/init.d/udpspeeder start
/etc/init.d/kcptun start
/etc/init.d/mosdns start
sleep 20
uci commit firewall
/etc/init.d/firewall restart
/etc/init.d/dropbear start

exit 0
